### ISSUE TITLE
Criar script para inicializar o banco de dados

### ISSUE THREAD

**Issue by SamuelNoB** [PI1-2024-1/PI1-KATIAU-docs#38]
Criar um script `.py` que será responsável por configurar um banco de dados SQLITE3.
* Caso o banco não exista criar um banco de nome `katiau.db`
* Caso não existam tabelas, criar tabelas
* Caso o banco e as tabelas existam, ignorar as etapas.

O script deverá rodar sempre que a api for iniciada a fim de garantir que o banco esteja sempre iniciado.

## Diagrama Lógico de Dados

![image](https://github.com/PI1-2024-1/PI1-KATIAU-docs/assets/48574832/8ab64e9d-e724-4a55-81be-5f788dadb785)

**Comment by brunna-martins** [comment]
Na tabela de Percursos, é possível adicionar duas novas colunas: "distPercorrida" e "tempoDecorrido", ambos do tipo Float. distPercorrida: distância total percorrida nesse percurso específico.
tempoDecorrido: tempo que o carrinho levou para fazer o percurso completo.
Esses dados serão inicializados com 0 e podem: 
- ser atualizados a cada novo registro de Telemetria (mais custoso);
- esperar até o fim do percurso para atualizar ambos os valores.
